name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Cowsay Program
      uses: actions/checkout@v4

    - name: List Repo Files
      run: ls -ltra

    - name: Executing Shell Script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh

    